# Generated by Django 3.2.9 on 2021-11-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitOften',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zone_manage.user')),
            ],
            options={
                'db_table': 'visit_often',
            },
        ),
        migrations.CreateModel(
            name='PredictionLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zone_manage.user')),
            ],
            options={
                'db_table': 'prediction_location',
            },
        ),
    ]
